# Generated by Django 3.2 on 2023-06-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweets_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=50)),
                ('uses', models.CharField(max_length=100)),
                ('tdesc', models.CharField(max_length=300)),
                ('topics', models.CharField(max_length=300)),
                ('sanalysis', models.CharField(max_length=300)),
                ('senderstatus', models.CharField(default='process', max_length=300)),
                ('ratings', models.IntegerField(default=0)),
                ('usefulcounts', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='review_model',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='review_model',
            name='sanalysis',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
        migrations.AddField(
            model_name='tweets_model',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remote_User.clientregister_model'),
        ),
    ]
